# This contains only GUI settings for GRC and is not meant for users to edit.
#
# GRC settings not accessible through the GUI are in config.conf under
# section [grc].

[main]
file_open = /home/aaron/git/meshtastic_sdr/gnuradio scripts/RX/Meshtastic_US_allPresets.grc
main_window_width = 1394
main_window_height = 1074
console_window_position = 803
blocks_window_position = 1088
variable_editor_position = 354

[files_recent]

[files_open]
files_open_0 = /home/aaron/git/meshtastic_sdr/gnuradio scripts/RX/Meshtastic_US_allPresets.grc

